name: StockMarket
main: com.yerti.stockmarket.StockMarket
version: 1.1
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  sm:
    description: Core StockMarket command.
    usage: /sm
  stock:
    description: Core StockMarket command.
    usage: /stock